# Unit-1 Data Analysis With Pandas

## Pandas Series

In [ ]:
import pandas as pd
a= [1,7,2] # list
myvar = pd.Series(a) # converts the list into column like showed below
print(myvar)
print(type(myvar))

# Access an item
print(myvar[0]) # accessed through index

0    1
1    7
2    2
dtype: int64
<class 'pandas.core.series.Series'>
1

#### Index params

In [1]:
import pandas as pd
a= [1,7,2] # list
myvar = pd.Series(a, index=['x','y','z']) # indexes give (use list, and same no. as the len of list)
print(myvar)
print(type(myvar))

# Access an item
print(myvar[0])

x    1
y    7
z    2
dtype: int64
<class 'pandas.core.series.Series'>
1

C:\Users\Dhruvil\AppData\Local\Temp\ipykernel_24656\872138288.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(myvar[0])

In [ ]:
import pandas as pd
student_name = ['ram','shyam','radha','seeta','geeta']
marks = [50,60,70,80,90]
# here we can only have 1 column  in series but we can allocate the other one as index

data = pd.Series(marks, index=student_name,name='Student Results')

print(data)

ram      50
shyam    60
radha    70
seeta    80
geeta    90
Name: Student Results, dtype: int64

#### using dict

In [ ]:
import pandas as pd
calories = {'day1':400, 'day2':380}
data = pd.Series(calories)
print(data)

day1    400
day2    380
dtype: int64

In [ ]:
import pandas as pd
calories = {'day1':400, 'day2':380}
data = pd.Series(calories, index=['day1']) # select specific keys
print(data)

day1    400
dtype: int64

### Attributes
    1. Size: as the name suggests dumbfuck
    2. dtype
    3. .name: get name of the dataframe
    4. index: return indexes
    5. values: array of values 
    6. is_unique: true if all values are diff or false

In [6]:
import pandas as pd
student_name = ['ram','shyam','radha','seeta','geeta']
marks = [50,60,70,80,90]
# here we can only have 1 column  in series but we can allocate the other one as index

data = pd.Series(marks, index=student_name,name='Student Results')

print(data)
print(data.size)

ram      50
shyam    60
radha    70
seeta    80
geeta    90
Name: Student Results, dtype: int64
5

In [7]:
data.dtype

dtype('int64')

In [8]:
data.name

'Student Results'

In [9]:
data.index

Index(['ram', 'shyam', 'radha', 'seeta', 'geeta'], dtype='object')

In [10]:
data.values

array([50, 60, 70, 80, 90])

In [11]:
data.is_unique

True

---

## Reading a csv

In [19]:
import pandas as pd
subs = pd.read_csv('subs.csv')
print(subs)
print(type(subs))

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>

In [17]:
import pandas as pd
subs = pd.read_csv('subs.csv').squeeze() # this will convert dataframe to series
print(subs)
print(type(subs))

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
import pandas as pd
subs = pd.read_csv('subs.csv').squeeze()
print(subs)
print(type(subs))
print(subs.describe())

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64
<class 'pandas.core.series.Series'>
count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

## Getting specific

In [8]:
print(subs.min())
print(subs.max())
print(subs.median())

33
396
123.0

In [3]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [7]:
subs[subs > 200].size

59

In [10]:
maxx = subs.max()
subs[subs == maxx].index

Index([330], dtype='int64')

### Another csv it has more than 1 column so sqeeze ain't gonna do shit

In [4]:
import pandas as pd
b = pd.read_csv('bollywood.csv',index_col='movie').squeeze()
b

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [2]:
b.head()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar

In [21]:
b.tail()

                                    lead
movie
Hum Tumhare Hain Sanam    Shah Rukh Khan
Aankhen (2002 film)     Amitabh Bachchan
Saathiya (film)             Vivek Oberoi
Company (film)                Ajay Devgn
Awara Paagal Deewana        Akshay Kumar

In [5]:
b['Why Cheat India']

'Emraan Hashmi'

### Slicing

In [6]:
b[-5::]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [7]:
b[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [9]:
# NEW
# through INdexs 
b[[0,1,3,4,8]]

C:\Users\Dhruvil\AppData\Local\Temp\ipykernel_28300\706786504.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b[[0,1,3,4,8]]

movie
Uri: The Surgical Strike               Vicky Kaushal
Battalion 609                            Vicky Ahuja
Why Cheat India                        Emraan Hashmi
Evening Shadows                     Mona Ambegaonkar
Manikarnika: The Queen of Jhansi      Kangana Ranaut
Name: lead, dtype: object

In [10]:
b.tail().values

array(['Shah Rukh Khan', 'Amitabh Bachchan', 'Vivek Oberoi', 'Ajay Devgn',
       'Akshay Kumar'], dtype=object)

### Check if a movie/lead exists

In [11]:
'2 states (2014 film)' in b

False

In [12]:
'Alia Bhatt' in b.values

True

## Count the amount of time a value has appeared

In [15]:
b.value_counts(ascending=True)

lead
Edwin Fernandes          1
Vikas Kalantri           1
Geetika Vidya Ohlyan     1
Prit Kamani              1
Attin Bhalla             1
                        ..
Sanjay Dutt             26
Salman Khan             31
Ajay Devgn              38
Amitabh Bachchan        45
Akshay Kumar            48
Name: count, Length: 566, dtype: int64

In [17]:
b.value_counts()

lead
Akshay Kumar            48
Amitabh Bachchan        45
Ajay Devgn              38
Salman Khan             31
Sanjay Dutt             26
                        ..
Tanishaa Mukerji         1
Tanuja                   1
Ankit                    1
Rakhee Gulzar            1
Geetika Vidya Ohlyan     1
Name: count, Length: 566, dtype: int64

## Using conditions for count

In [26]:
x = b.value_counts()
x[ x> 20] # can't directly do these in b will have to use a storage

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64

In [ ]:
# shitty way but works fine
b [b.values== 'Akshay Kumar' ].size

48

In [31]:
marks = {'ram': 55, 'Shyam': 60, 'Seeta': 70, 'geeta': 65}
marks_series = pd.Series(marks, name='Student Prof') 

print(marks_series)

ram      55
Shyam    60
Seeta    70
geeta    65
Name: Student Prof, dtype: int64

In [32]:
list(marks_series)

[55, 60, 70, 65]

In [33]:
dict(marks_series)

{'ram': np.int64(55),
 'Shyam': np.int64(60),
 'Seeta': np.int64(70),
 'geeta': np.int64(65)}

In [34]:
marks_series[1] = 100

C:\Users\Dhruvil\AppData\Local\Temp\ipykernel_28300\3104910507.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1] = 100

In [35]:
marks_series

ram       55
Shyam    100
Seeta     70
geeta     65
Name: Student Prof, dtype: int64

In [36]:
100 + marks_series

ram      155
Shyam    200
Seeta    170
geeta    165
Name: Student Prof, dtype: int64

In [37]:
marks_series

ram       55
Shyam    100
Seeta     70
geeta     65
Name: Student Prof, dtype: int64

In [38]:
marks_series >= 100 # return boolean values infornt of index

ram      False
Shyam     True
Seeta    False
geeta    False
Name: Student Prof, dtype: bool

In [40]:
import pandas as pd

a = pd.Series([2,4,6,8,10])
b = pd.Series([1,3,5,7,10])

print(a-b)

0    1
1    1
2    1
3    1
4    0
dtype: int64

In [41]:
print(a+b)

0     3
1     7
2    11
3    15
4    20
dtype: int64

In [42]:
print(a*b)

0      2
1     12
2     30
3     56
4    100
dtype: int64

In [43]:
print(a/b)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

In [44]:
print(a==b)

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [45]:
print(a>b)

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [46]:
print(a<b)

0    False
1    False
2    False
3    False
4    False
dtype: bool

# DataFrame

In [48]:
import pandas as pd
data = {
    'calories': [420,380,390,400],
    'duration': [50,40,45,48]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45
3       400        48

In [49]:
# access an element
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

### iloc vs loc: iloc sees int as an index, where loc can take string as an input too for key

In [ ]:
df.iloc['day1']

TypeError: Cannot index by location index with a non-integer key

In [51]:
df['calories'] # this will be considered as series tho

0    420
1    380
2    390
3    400
Name: calories, dtype: int64

In [52]:
df.loc[[0,1]]

   calories  duration
0       420        50
1       380        40

In [53]:
import pandas as pd
data = {
    'calories': [420,380,390,400],
    'duration': [50,40,45,48]
}
df = pd.DataFrame(data, index=['day1', 'day2', 'day3', 'day4'])

In [54]:
df.loc['day1']

calories    420
duration     50
Name: day1, dtype: int64

In [56]:
import pandas as pd

data = {
    'Name': ['Alice','Bob', 'Charlie'],
    'Age': [25,30,35],
    'City': ['New York','Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [57]:
df.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [58]:
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [ ]:
df.loc[0:2] # include ending point

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df.iloc[0:2] # excludes ending point

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

In [ ]:
df.loc[(df.Age > 26) & (df.City == 'Chicago')]

      Name  Age     City
2  Charlie   35  Chicago

## Adding Values to a DF

In [67]:
import pandas as pd

data = {
    'A': [1,2,3,4],
    'B': [5,6,7,8]
}
df = pd.DataFrame(data, index=['r1','r2','r3','r4'])
df

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [70]:
df.loc['r2':'r4','B'] = [1,2,3] # params silce for index, Column name, => value to edit

In [71]:
df

    A  B
r1  1  5
r2  2  1
r3  3  2
r4  4  3

In [74]:
# adding a new column named c
df['c'] = [10,20,30,40]
df

    A  B   c
r1  1  5  10
r2  2  1  20
r3  3  2  30
r4  4  3  40

In [76]:
df.loc[df['A']==1, 'new_(o)'] = 'Zero'
df

    A  B   c new_(o)
r1  1  5  10    Zero
r2  2  1  20     NaN
r3  3  2  30     NaN
r4  4  3  40     NaN

In [78]:
df.loc[len(df)] = [10,11,12,13]
df

     A   B   c new_(o)
r1   1   5  10    Zero
r2   2   1  20     NaN
r3   3   2  30     NaN
r4   4   3  40     NaN
4   10  11  12      13
5   10  11  12      13

##### settting index

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice','Bob', 'Charlie'],
    'Age': [25,30,35],
    'City': ['New York','Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
df.set_index('Name', drop=False) # won't update the df

In [9]:
df.set_index('Name', drop=False, inplace=True) # inplace will update the df
df

            Name  Age         City
Name
Alice      Alice   25     New York
Bob          Bob   30  Los Angeles
Charlie  Charlie   35      Chicago

In [10]:
data = {
    'Region': ['North','North','South','South'],
    'City': ['NY','LA','Miami','Houston'],
    'Population': [8.4,3.9,0.4,2.3]
}

df = pd.DataFrame(data)
df.set_index(['Region','City'])

                Population
Region City
North  NY              8.4
       LA              3.9
South  Miami           0.4
       Houston         2.3

In [11]:
data = {
    'Region': ['North','North','South','South'],
    'City': ['NY','LA','Miami','Houston']
}

df = pd.DataFrame(data, index=['a','b','c','d'])
df

  Region     City
a  North       NY
b  North       LA
c  South    Miami
d  South  Houston

In [12]:
df_reset = df.reset_index()
df_reset

  index Region     City
0     a  North       NY
1     b  North       LA
2     c  South    Miami
3     d  South  Houston

In [13]:
data = {
    'Region': ['North','North','South','South'],
    'City': ['NY','LA','Miami','Houston'],
    'Age': [30,35,40,45]
}


df = pd.DataFrame(data, index=['a','b','c','d'])
df

  Region     City  Age
a  North       NY   30
b  North       LA   35
c  South    Miami   40
d  South  Houston   45

In [14]:
df.columns

Index(['Region', 'City', 'Age'], dtype='object')

In [15]:
df.size

12

In [16]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [17]:
df.values

array([['North', 'NY', 30],
       ['North', 'LA', 35],
       ['South', 'Miami', 40],
       ['South', 'Houston', 45]], dtype=object)

In [18]:
df.ndim

2

In [19]:
df.shape

(4, 3)

In [20]:
df.dtypes

Region    object
City      object
Age        int64
dtype: object

## Data Cleaning 
#### Methods to remove null values:
    1. delete complete row with NaN
    2. Fill with dummy data
    3. Replace it with mean,median , values

In [1]:
# Dataset
import numpy as np 
import pandas as pd
sales_data = pd.DataFrame({'Name': ['William', 'Emma', 'Sofia', 'Markus', 'Edward', 'Thomas', 'Ethan', np.nan , 'Arun', 'Ankita', 'Paule'],
                            'Region': [np.nan, 'North', 'East', np.nan, 'West', 'West', 'South', np.nan, 'West', 'East', 'South'],
                            'Sales': [np.nan, 12000, 15000, np.nan, 18000, 20000, 22000, np.nan, 25000, 28000, 30000],
                            'Expense': [np.nan, 1000, 1500, np.nan, 2000, 2500, 3000, np.nan, 3500, 4000, 4500]})

In [2]:
sales_data

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
7       NaN    NaN      NaN      NaN
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [4]:
sales_data.isna().sum() # to find the null values for each column

Name       1
Region     3
Sales      3
Expense    3
dtype: int64

### 1. TO delete rows with missing values

In [ ]:
# 1. TO delete rows with missing values
sales_data.dropna()

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [ ]:
sales_data.dropna(thresh=2) # it means atleast 2 valid data is needed

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [7]:
sales_data.dropna(thresh=1) # it means atleast 2 valid data is needed

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [ ]:
sales_data.dropna(how='any') # default value is this any

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [ ]:
sales_data.dropna(how='all') # drop rows where all values are missing

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [12]:
sales_data.dropna(subset=['Name'])

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [13]:
sales_data.dropna(subset=['Name', 'Expense'])

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [ ]:
sales_data.dropna(axis=0) # delete rows with missing values

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [ ]:
sales_data.dropna(axis=1) # delete columns with missing values

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

2. ### Fill with dummy data

In [ ]:
sales_data.fillna(0) # fill missing values with 0 (can use any other values)

       Name Region    Sales  Expense
0   William      0      0.0      0.0
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus      0      0.0      0.0
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
7         0      0      0.0      0.0
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [17]:
# to fillna columnwise
sales_data['Sales'].fillna(0)

0         0.0
1     12000.0
2     15000.0
3         0.0
4     18000.0
5     20000.0
6     22000.0
7         0.0
8     25000.0
9     28000.0
10    30000.0
Name: Sales, dtype: float64

In [18]:
# to fillna columnwise
sales_data['Name'].fillna('Guest')

0     William
1        Emma
2       Sofia
3      Markus
4      Edward
5      Thomas
6       Ethan
7       Guest
8        Arun
9      Ankita
10      Paule
Name: Name, dtype: object

### Replace with mean , median values

In [ ]:
sales_data['Sales'].fillna(sales_data['Sales'].mean()) # Fill the data with the mean of respective column

0     21250.0
1     12000.0
2     15000.0
3     21250.0
4     18000.0
5     20000.0
6     22000.0
7     21250.0
8     25000.0
9     28000.0
10    30000.0
Name: Sales, dtype: float64

In [20]:
sales_data['Sales'].fillna(sales_data['Sales'].median())

0     21000.0
1     12000.0
2     15000.0
3     21000.0
4     18000.0
5     20000.0
6     22000.0
7     21000.0
8     25000.0
9     28000.0
10    30000.0
Name: Sales, dtype: float64

In [32]:
import numpy as np
import pandas as pd

autompg = pd.read_csv("auto-mpg.csv")

autompg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [33]:
autompg.loc[autompg['horsepower']=='?'] 
autompg['horsepower'].replace('?',np.nan, inplace=True)
autompg['horsepower'] = autompg['horsepower'].astype(float)

C:\Users\Dhruvil\AppData\Local\Temp\ipykernel_18224\2272299561.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  autompg['horsepower'].replace('?',np.nan, inplace=True)

In [ ]:
autompg['horsepower'].isnull().sum()

np.int64(6)

In [41]:
autompg.dropna(subset=['horsepower'], inplace=True)
autompg['horsepower'].isnull().sum()

np.int64(0)

In [40]:
autompg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,1,chevy s-10

In [42]:
autompg.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    object
dtypes: float64(4), int64(4), object(1)
memory usage: 30.6+ KB

In [43]:
# To update datatype of a column
autompg['horsepower'] = autompg['horsepower'].astype(float)

In [46]:
autompg.drop('car name', axis=1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,1
1,15.0,8,350.0,165.0,3693,11.5,70,1
2,18.0,8,318.0,150.0,3436,11.0,70,1
3,16.0,8,304.0,150.0,3433,12.0,70,1
4,17.0,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,1
394,44.0,4,97.0,52.0,2130,24.6,82,2
395,32.0,4,135.0,84.0,2295,11.6,82,1
396,28.0,4,120.0,79.0,2625,18.6,82,1
397,31.0,4,119.0,82.0,2720,19.4,82,1

### How to Find Outliers

Interquartile range (IQR) = Q3(75%) - Q1(25%) 

Now using eq we define a range a lower and a hgiher range if the value is out of that range then it's an outlier

lower_value => q1 - 1.5 * IQR 
higer_value => q3 + 1.5 * IQR

In [48]:
import numpy as np
import pandas as pd

def find_outliers(ds,col):
    q1 = ds[col].quantile(0.25) # fidnging 25%
    q3 = ds[col].quantile(0.75)
    IQR = q3 - q1
    low_val = q1 - 1.5 * IQR
    upper_val = q3 + 1.5 * IQR
    print(f'Low: {low_val}, High: {upper_val}')

    ds = ds.loc[(ds[col] < low_val) | (ds[col]> upper_val)]
    return ds

df = pd.read_csv('auto-mpg.csv')
find_outliers(df,'mpg')

Low: 0.25, High: 46.25

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
322,46.6,4,86.0,65,2110,17.9,80,3,mazda glc

In [49]:
find_outliers(df,'acceleration')

Low: 8.8, High: 22.2

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
59,23.0,4,97.0,54,2254,23.5,72,2,volkswagen type 3
299,27.2,4,141.0,71,3190,24.8,79,2,peugeot 504
326,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup

In [53]:
import numpy as np
import pandas as pd

def remove_outliers(ds,col):
    q1 = ds[col].quantile(0.25) # fidnging 25%
    q3 = ds[col].quantile(0.75)
    IQR = q3 - q1
    low_val = q1 - 1.5 * IQR
    upper_val = q3 + 1.5 * IQR
    print(f'Low: {low_val}, High: {upper_val}')

    ds = ds.loc[(ds[col] > low_val) & (ds[col] < upper_val)]
    return ds

df = pd.read_csv('auto-mpg.csv')
remove_outliers(df,'mpg')

Low: 0.25, High: 46.25

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

### Drop and Remove Duplicates

In [2]:
import pandas as pd
data = {'A': ['TeamA', 'TeamB', 'TeamB', 'TeamC', 'TeamA'],
        'B': [50,40,40,30,50],
        'C': [True,False,False,False,True]}
df = pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [55]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [56]:
df.duplicated(keep='first')

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [57]:
df.duplicated(keep='last')

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [4]:
df.drop_duplicates()

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [5]:
df.drop_duplicates(inplace=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [6]:
df = df.reset_index(drop=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamC  30  False

## Sort Values
-- Used to sort a DF or series by the values along a specific axis default(asc)

In [4]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice','Bob','Charlie','David'],
    'Score': [88,92,85,90]
})

df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     85
3    David     90

In [5]:
sorted_df = df.sort_values(by='Score')
sorted_df

      Name  Score
2  Charlie     85
0    Alice     88
3    David     90
1      Bob     92

In [6]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     85
1      Bob     92
0    Alice     88

In [7]:
df.set_index('Name',inplace=True)
df

         Score
Name
Alice       88
Bob         92
Charlie     85
David       90

In [8]:
df.sort_index(ascending=False)

         Score
Name
David       90
Charlie     85
Bob         92
Alice       88

## apply()

In [9]:
# apply()
import pandas as pd
s  = pd.Series([35,67,90,45])
def pass_fail(x):
    return 'pass' if x>=50 else 'fail'

results = s.apply(pass_fail)
results

0    fail
1    pass
2    pass
3    fail
dtype: object

In [ ]:
df = pd.DataFrame({
    'Physics': [60,70,80],
    'Chemistry': [65,75,85],
    'Maths': [70,80,90]
})
result = df.apply(sum) # default Function sum that js adds the values
print(result)

Physics      210
Chemistry    225
Maths        240
dtype: int64

In [11]:
aresult = df.apply(sum, axis=1) # add rows data instead of column
aresult

0    195
1    225
2    255
dtype: int64

In [13]:
# using lambda
meanresult = df.apply(lambda x: x.mean())
print(meanresult)

Physics      70.0
Chemistry    75.0
Maths        80.0
dtype: float64

In [14]:
## actual usage

df['total'] = df.apply(sum, axis=1)
df

   Physics  Chemistry  Maths  total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [15]:
def grade(x):
    if x>=250 :
        return 'A'
    elif x>=200 :
        return 'B'
    else :
        return 'C'

df['grade'] = df['total'].apply(grade)
df

   Physics  Chemistry  Maths  total grade
0       60         65     70    195     C
1       70         75     80    225     B
2       80         85     90    255     A

In [18]:
# topper
toplist = df.sort_values(by='grade')
toplist

   Physics  Chemistry  Maths  total grade
2       80         85     90    255     A
1       70         75     80    225     B
0       60         65     70    195     C

In [19]:
import pandas as pd 
df = pd.DataFrame({'width': [1,2],
                    'height': [3,4]})
            
def get_stats(row):
    return [row['width']*row['height'], 2*(row['width']+ row['height'])]

In [20]:
df.apply(get_stats, axis=1, result_type='expand')

   0   1
0  3   8
1  8  12

In [22]:
df.apply(get_stats, axis=1, result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

In [24]:
df.apply(get_stats, axis=1, result_type='broadcast')

   width  height
0      3       8
1      8      12

In [25]:
import pandas as pd
def add_values(x,y,z):
    return x+y+z 
df = pd.DataFrame({
    'A': [1,2],
    'B': [10,20]
})

In [ ]:
df = df.apply(add_values, args=(1,2)) # x will be from dataframe and y,z will be fromt args=
print(df)

   A   B
0  4  13
1  5  23

In [27]:
def add_values(x,m):
    return x*m 
df = df.apply(add_values,m=10) # without args
print(df)

    A    B
0  40  130
1  50  230

## astype()

In [28]:
import pandas as pd
df = pd.DataFrame({
    'A': ['1','2','3'],
    'B': ['4','5','6']
})
print(df.dtypes)

A    object
B    object
dtype: object

In [29]:
df['A'] = df['A'].astype(int)
print(df.dtypes)

A     int64
B    object
dtype: object

## replace

In [30]:
import pandas as pd
df = pd.DataFrame({
    'Marks': [80,85,0,90],
    'Attendance': [75,80,0,85],
    'Grade': ["A", "B", "F", "A"]
})
result = df.replace(0,60)
result

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [31]:
results = df.replace([80,75],[90,80])
results

   Marks  Attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A