In [2]:
import pandas as pd

In [17]:
a = pd.read_csv("bollywood.csv",index_col="movie").squeeze()

In [18]:
a[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: str

In [19]:
a[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: str

In [20]:
# a[[0,1,3,4,5]] will give error in new versions of pandas. Use a.iloc[[0,1,3,4,5]] instead.

In [21]:
a.iloc[[0,1,3,4,8]]

movie
Uri: The Surgical Strike               Vicky Kaushal
Battalion 609                            Vicky Ahuja
Why Cheat India                        Emraan Hashmi
Evening Shadows                     Mona Ambegaonkar
Manikarnika: The Queen of Jhansi      Kangana Ranaut
Name: lead, dtype: str

In [22]:
"2 States (2014 film)" in a

True

In [23]:
"Alia Bhatt" in a.values

True

In [24]:
a.value_counts(ascending=True)

lead
Geetika Vidya Ohlyan     1
Prit Kamani              1
Abhimanyu Dasani         1
Talha Arshad Reshi       1
Garima Agarwal           1
                        ..
Sanjay Dutt             26
Salman Khan             31
Ajay Devgn              38
Amitabh Bachchan        45
Akshay Kumar            48
Name: count, Length: 566, dtype: int64

In [25]:
b = a.value_counts()
b[b>20]  # we cannot put direct function in this.....

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64

In [28]:
a[a.values =="Akshay Kumar"].size

48

In [30]:
marks ={'ram':55,'shyam':60,'seeta':70,'geeta':65}
m = pd.Series(marks, name="Students")
m

ram      55
shyam    60
seeta    70
geeta    65
Name: Students, dtype: int64

In [31]:
list(m)

[55, 60, 70, 65]

In [32]:
dict(m)

{'ram': np.int64(55),
 'shyam': np.int64(60),
 'seeta': np.int64(70),
 'geeta': np.int64(65)}

In [ ]:
m[1]=100
m

ram       55
shyam    100
seeta     70
geeta     65
1        100
Name: Students, dtype: int64

In [35]:
100+m

ram      155
shyam    200
seeta    170
geeta    165
1        200
Name: Students, dtype: int64

In [36]:
m

ram       55
shyam    100
seeta     70
geeta     65
1        100
Name: Students, dtype: int64

In [37]:
m>=100

ram      False
shyam     True
seeta    False
geeta    False
1         True
Name: Students, dtype: bool

Conditional and arthmetical operations

In [38]:
a= pd.Series([2,4,6,8,10])
b= pd.Series([1,3,5,7,10])

In [39]:
a+b

0     3
1     7
2    11
3    15
4    20
dtype: int64

In [40]:
a-b

0    1
1    1
2    1
3    1
4    0
dtype: int64

In [41]:
a*b

0      2
1     12
2     30
3     56
4    100
dtype: int64

In [42]:
a/b

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

In [43]:
a==b

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [44]:
a>b

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [45]:
a<b

0    False
1    False
2    False
3    False
4    False
dtype: bool

## DataFrame

In [64]:
data = {
    'calories':["111",222,333,444],
    'duration':[50,60,70,80]
}
df = pd.DataFrame(data)
df

  calories  duration
0      111        50
1      222        60
2      333        70
3      444        80

In [65]:
df.loc[0]

calories    111
duration     50
Name: 0, dtype: object

In [66]:
df.iloc[0]

calories    111
duration     50
Name: 0, dtype: object

In [67]:
df['calories']

0    111
1    222
2    333
3    444
Name: calories, dtype: object

In [68]:
df['duration']

0    50
1    60
2    70
3    80
Name: duration, dtype: int64

In [69]:
df.loc[[0,1]]

  calories  duration
0      111        50
1      222        60

In [70]:
data = {
    'calories':["111",222,333,444],
    'duration':[50,60,70,80]
}
df = pd.DataFrame(data,index=["day1","day2","day3","day4"])
df

     calories  duration
day1      111        50
day2      222        60
day3      333        70
day4      444        80

In [76]:
# df.iloc["day1"] gives error because iloc is used for integer based indexing. Use df.loc["day1"] instead.

In [77]:
df.loc["day1"]

calories    111
duration     50
Name: day1, dtype: object

In [78]:
data = {'Name':["Alice","Bob","Charlie"],
        'Age':[25,30,35],
        'City':["New York","Los Angeles","Chicago"]}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [79]:
df.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [80]:
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [ ]:
df.loc[0:1] # last point will be include

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

In [ ]:
df.iloc[0:1] # last point will be exclude

    Name  Age      City
0  Alice   25  New York

In [91]:
df[(df.Age>26) & (df.City=="Chicago")]

      Name  Age     City
2  Charlie   35  Chicago

In [95]:
data  = {"A":[1,2,3,4],"B":[5,6,7,8]}
df = pd.DataFrame(data, index=["r1","r2","r3","r4"])
df

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [96]:
df.loc["r2":"r4","B"]=99
df

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [99]:
df.iloc[1:3,0]= 0
df

    A   B
r1  1   5
r2  0  99
r3  0  99
r4  4  99

In [101]:
df["C"]=[10,20,30,40]
df

    A   B   C
r1  1   5  10
r2  0  99  20
r3  0  99  30
r4  4  99  40

In [103]:
df.loc[df["A"]==0,"new_col"]="zero"
df

    A   B   C new_col
r1  1   5  10    zero
r2  0  99  20    zero
r3  0  99  30    zero
r4  4  99  40     NaN

In [105]:
df.loc[len(df)]=[11,22,33,44]
df

     A   B   C new_col
r1   1   5  10    zero
r2   0  99  20    zero
r3   0  99  30    zero
r4   4  99  40     NaN
4   11  22  33      44
5   11  22  33      44

In [106]:
# set_index()

data = {'Name':["Alice","Bob","Charlie"],
        'Age':[25,30,35],
        'City':["New York","Los Angeles","Chicago"]}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [111]:
df.set_index("Name", drop=False)

            Name  Age         City
Name
Alice      Alice   25     New York
Bob          Bob   30  Los Angeles
Charlie  Charlie   35      Chicago

In [116]:
df.set_index("Name", drop=False,inplace=True)
df

            Name  Age         City
Name
Alice      Alice   25     New York
Bob          Bob   30  Los Angeles
Charlie  Charlie   35      Chicago

In [120]:
data = {"Region":["n","s","e","w"],
      "city":['ny',"la","miami","chi"],
      "population":[10,20,30,40]
}
df= pd.DataFrame(data)
df.set_index("Region", inplace=True)
df

         city  population
Region
n          ny          10
s          la          20
e       miami          30
w         chi          40

In [122]:
df.reset_index(drop=True)

    city  population
0     ny          10
1     la          20
2  miami          30
3    chi          40

DataFrame Attributes

In [124]:
df.columns

Index(['city', 'population'], dtype='str')

In [126]:
df.index

Index(['n', 's', 'e', 'w'], dtype='str', name='Region')

In [127]:
df.size

8

In [128]:
df.values

array([['ny', 10],
       ['la', 20],
       ['miami', 30],
       ['chi', 40]], dtype=object)

In [129]:
df.ndim

2

In [130]:
df.shape

(4, 2)

In [132]:
df.dtypes

city            str
population    int64
dtype: object