In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Data Cleaning

1. missing values
2. methods to remove missing values:
    1. Delete complete row with NaN
    2. fill with dummy data
    3. replace it with mean, median, mode

In [4]:
sales_data = pd.DataFrame({'Name': ['William', 'Emma', 'Sofia', 'Markus', 'Edward', 'Thomas', 'Ethan', np.nan , 'Arun', 'Ankita', 'Paule'],
                            'Region': [np.nan, 'North', 'East', np.nan, 'West', 'West', 'South', np.nan, 'West', 'East', 'South'],
                            'Sales': [np.nan, 12000, 15000, np.nan, 18000, 20000, 22000, np.nan, 25000, 28000, 30000],
                            'Expense': [np.nan, 1000, 1500, np.nan, 2000, 2500, 3000, np.nan, 3500, 4000, 4500]})

sales_data

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
7       NaN    NaN      NaN      NaN
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [5]:
sales_data.isna() # isnull() is also valid

     Name  Region  Sales  Expense
0   False    True   True     True
1   False   False  False    False
2   False   False  False    False
3   False    True   True     True
4   False   False  False    False
5   False   False  False    False
6   False   False  False    False
7    True    True   True     True
8   False   False  False    False
9   False   False  False    False
10  False   False  False    False

In [6]:
sales_data.isna().sum()

Name       1
Region     3
Sales      3
Expense    3
dtype: int64

In [7]:
sales_data.dropna()

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [8]:
sales_data.dropna(thresh=2) # thresh means to check how many valid data is present

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [9]:
sales_data.dropna(how='all')

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [11]:
sales_data.dropna(subset=['Sales','Expense'])

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [ ]:
sales_data.dropna(axis=0) #normal check null value

      Name Region    Sales  Expense
1     Emma  North  12000.0   1000.0
2    Sofia   East  15000.0   1500.0
4   Edward   West  18000.0   2000.0
5   Thomas   West  20000.0   2500.0
6    Ethan  South  22000.0   3000.0
8     Arun   West  25000.0   3500.0
9   Ankita   East  28000.0   4000.0
10   Paule  South  30000.0   4500.0

In [13]:
sales_data.dropna(axis=1) #normal check null value

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
sales_data

       Name Region    Sales  Expense
0   William    NaN      NaN      NaN
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus    NaN      NaN      NaN
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
7       NaN    NaN      NaN      NaN
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [16]:
sales_data.fillna(0)

       Name Region    Sales  Expense
0   William      0      0.0      0.0
1      Emma  North  12000.0   1000.0
2     Sofia   East  15000.0   1500.0
3    Markus      0      0.0      0.0
4    Edward   West  18000.0   2000.0
5    Thomas   West  20000.0   2500.0
6     Ethan  South  22000.0   3000.0
7         0      0      0.0      0.0
8      Arun   West  25000.0   3500.0
9    Ankita   East  28000.0   4000.0
10    Paule  South  30000.0   4500.0

In [17]:
sales_data['Name'].fillna('Guest')

0     William
1        Emma
2       Sofia
3      Markus
4      Edward
5      Thomas
6       Ethan
7       Guest
8        Arun
9      Ankita
10      Paule
Name: Name, dtype: str

In [19]:
sales_data['Sales'].fillna(sales_data['Sales'].mean())

0     21250.0
1     12000.0
2     15000.0
3     21250.0
4     18000.0
5     20000.0
6     22000.0
7     21250.0
8     25000.0
9     28000.0
10    30000.0
Name: Sales, dtype: float64

In [20]:
sales_data['Sales'].fillna(sales_data['Sales'].median())

0     21000.0
1     12000.0
2     15000.0
3     21000.0
4     18000.0
5     20000.0
6     22000.0
7     21000.0
8     25000.0
9     28000.0
10    30000.0
Name: Sales, dtype: float64

In [37]:
df =pd.read_csv('auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [39]:
df=df[df['horsepower']!='?']
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    str
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    str
dtypes: float64(3), int64(4), str(2)
memory usage: 30.6 KB

In [41]:
df['horsepower']=df['horsepower'].astype('int64')

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    int64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    str
dtypes: float64(3), int64(5), str(1)
memory usage: 30.6 KB

In [43]:
df.drop('car name',axis=1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1
394,44.0,4,97.0,52,2130,24.6,82,2
395,32.0,4,135.0,84,2295,11.6,82,1
396,28.0,4,120.0,79,2625,18.6,82,1
397,31.0,4,119.0,82,2720,19.4,82,1