sort_values:


 used to sort a DF or series by the values along a specific axis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame({'name':["alice","bob","charlie","david"],
                   'score':[88,92,85,90]})
df

      name  score
0    alice     88
1      bob     92
2  charlie     85
3    david     90

In [3]:
df.sort_values(by="score")

      name  score
2  charlie     85
0    alice     88
3    david     90
1      bob     92

In [4]:
df.sort_values(by="score",ascending=False)

      name  score
1      bob     92
3    david     90
0    alice     88
2  charlie     85

In [5]:
df.sort_index(ascending=False)

      name  score
3    david     90
2  charlie     85
1      bob     92
0    alice     88

apply()

used to run multiple data in a function

In [6]:
s= pd.Series([35,67,90,45])
def pass_fail(x):
    return 'pass' if x>=50 else 'fail'

result = s.apply(pass_fail)
result

0    fail
1    pass
2    pass
3    fail
dtype: str

In [19]:
df =pd.DataFrame({'Physics':[60,70,80],
                  'chemistry':[65,75,85],
                  'maths':[70,80,90]})
result= df.apply(sum)
result

Physics      210
chemistry    225
maths        240
dtype: int64

In [20]:
result= df.apply(sum,axis=1)
result

0    195
1    225
2    255
dtype: int64

In [21]:
result= df.apply(lambda x:x.mean())
result

Physics      70.0
chemistry    75.0
maths        80.0
dtype: float64

In [22]:
df['total']= df.apply(sum,axis=1)
df

   Physics  chemistry  maths  total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [25]:
def grade(total):
    if total>=250:
        return "A"
    elif total>=200:
        return "B"
    else :
        return "C"
    
df["grades"]=df["total"].apply(grade)
df

   Physics  chemistry  maths  total grades
0       60         65     70    195      C
1       70         75     80    225      B
2       80         85     90    255      A

In [27]:
df= pd.DataFrame({'width':[1,2,3],
                  'height':[4,5,6]})
def get_stats(row):
    return [row['width']*row['height'],2*(row['width'])]
df.apply(get_stats, axis=1, result_type='expand')

    0  1
0   4  2
1  10  4
2  18  6

In [28]:
df.apply(get_stats, axis=1, result_type='reduce')

0     [4, 2]
1    [10, 4]
2    [18, 6]
dtype: object

In [29]:
df.apply(get_stats, axis=1, result_type='broadcast')

   width  height
0      4       2
1     10       4
2     18       6

In [30]:
def add_values(x,y,z):
    return x+y+z 
df = pd.DataFrame({
    'A': [1,2],
    'B': [10,20]
})

In [31]:
df = df.apply(add_values, args=(1,2)) # x will be from dataframe and y,z will be fromt args=
print(df)

   A   B
0  4  13
1  5  23

In [32]:
def add_values(x,m):
    return x*m 
df = df.apply(add_values,m=10) # without args
print(df)

    A    B
0  40  130
1  50  230

astype()

In [33]:
df = pd.DataFrame({
    'A': ['1','2','3'],
    'B': ['4','5','6']
})
print(df.dtypes)

A    str
B    str
dtype: object

In [34]:
df['A'] = df['A'].astype(int)
print(df.dtypes)

A    int64
B      str
dtype: object

replace()

In [35]:
df = pd.DataFrame({
    'Marks': [80,85,0,90],
    'Attendance': [75,80,0,85],
    'Grade': ["A", "B", "F", "A"]
})
result = df.replace(0,60)
result

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [36]:
results = df.replace([80,75],[90,80])
results

   Marks  Attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A