In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

concat function

In [5]:
df1 = pd.DataFrame({"A":[1,2],"B":[3,4]})
df2 = pd.DataFrame({"A":[5,6],"C":[7,8]})
result = pd.concat([df1,df2],axis=0)
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [6]:
result = pd.concat([df1,df2],axis=1)
result

   A  B  A  C
0  1  3  5  7
1  2  4  6  8

In [7]:
result = pd.concat([df1,df2],axis=0,join="outer")
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [8]:
result = pd.concat([df1,df2],axis=0,join="inner")
result

   A
0  1
1  2
0  5
1  6

In [10]:
result = pd.concat([df1,df2],axis=0,ignore_index=True)
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0

In [12]:
df1 = pd.DataFrame({"E":[1,2],"B":[3,4]})
df2 = pd.DataFrame({"C":[5,6],"D":[7,8]})
result = pd.concat([df1,df2],sort=True)
result

     B    C    D    E
0  3.0  NaN  NaN  1.0
1  4.0  NaN  NaN  2.0
0  NaN  5.0  7.0  NaN
1  NaN  6.0  8.0  NaN

merge function

In [14]:
df1 = pd.DataFrame({'Employee': ['A','B','C'],
                    'Department': ['IT', 'HR', 'Finance']})

df2 = pd.DataFrame({'Employee': ['A','B','D'],
                    'Salary': [50000,4000,30000]})

result = pd.merge(df1,df2,on ="Employee")
result

  Employee Department  Salary
0        A         IT   50000
1        B         HR    4000

In [15]:
result = pd.merge(df1,df2,on ="Employee",how="outer")
result

  Employee Department   Salary
0        A         IT  50000.0
1        B         HR   4000.0
2        C    Finance      NaN
3        D        NaN  30000.0

In [ ]:
result = pd.merge(df1,df2,on ="Employee",how="left")
result

  Employee Department   Salary
0        A         IT  50000.0
1        B         HR   4000.0
2        C    Finance      NaN

In [17]:
result = pd.merge(df1,df2,on ="Employee",how="right")
result

  Employee Department  Salary
0        A         IT   50000
1        B         HR    4000
2        D        NaN   30000

In [18]:
dt1 = pd.DataFrame({
    'Emp_ID': [101,102,103],
    'Name': ['Amit', 'Riya', 'John'],
    'Salary': [50000, 66000, 55000]
})
dt2 = pd.DataFrame({
    'Emp_ID': [101,102,104],
    'Name': ['Amit', 'Riya', 'David'],
    'Salary': [57000, 96000, 75000]
})

result = pd.merge(dt1, dt2, on='Emp_ID')
result

   Emp_ID Name_x  Salary_x Name_y  Salary_y
0     101   Amit     50000   Amit     57000
1     102   Riya     66000   Riya     96000

In [19]:

result = pd.merge(dt1, dt2, on='Emp_ID',suffixes=('_left', '_right'))
result

   Emp_ID Name_left  Salary_left Name_right  Salary_right
0     101      Amit        50000       Amit         57000
1     102      Riya        66000       Riya         96000

In [22]:
dt1 = pd.DataFrame({
    'Emp_ID': [101,102,103],
    'Name': ['Amit', 'Riya', 'John']
})
dt2 = pd.DataFrame({
    'ID': [101,102,104],
    'Salary': [57000, 96000, 75000]
})

result = pd.merge(dt1, dt2, left_on='Emp_ID', right_on='ID')
result

   Emp_ID  Name   ID  Salary
0     101  Amit  101   57000
1     102  Riya  102   96000

In [29]:
dt1 = pd.DataFrame({
    'Name': ['Amit', 'Riya', 'John'],
     "index":[100,101,102]
     })
dt2 = pd.DataFrame({
    'Salary': [57000, 96000, 75000]
},index=[100,101,102])

result= pd.merge(dt1,dt2, left_on="index", right_index=True)
result

   Name  index  Salary
0  Amit    100   57000
1  Riya    101   96000
2  John    102   75000

groupby()

In [30]:
df = pd.DataFrame({
    'Product Category': ["Elec","Furni","Elec","Furni"],
    'Sales': [200,150,300,100]
})
df

  Product Category  Sales
0             Elec    200
1            Furni    150
2             Elec    300
3            Furni    100

In [35]:
result = df.groupby('Product Category')["Sales"].sum()
result

Product Category
Elec     500
Furni    250
Name: Sales, dtype: int64

In [36]:
result = df.groupby('Product Category')["Sales"].mean()
result

Product Category
Elec     250.0
Furni    125.0
Name: Sales, dtype: float64

In [37]:
result = df.groupby('Product Category')["Sales"].median()
result

Product Category
Elec     250.0
Furni    125.0
Name: Sales, dtype: float64

In [38]:
result = df.groupby('Product Category')["Sales"].describe()
result

                  count   mean        std    min    25%    50%    75%    max
Product Category
Elec                2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Furni               2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [41]:
result = df.groupby('Product Category')["Sales"].sample(2)
result

2    300
0    200
1    150
3    100
Name: Sales, dtype: int64

In [42]:
result = df.groupby('Product Category')["Sales"].groups
result

{'Elec': [0, 2], 'Furni': [1, 3]}

In [45]:
result = df.groupby('Product Category',as_index=True,sort=True)["Sales"].count()
result

Product Category
Elec     2
Furni    2
Name: Sales, dtype: int64

In [46]:
result = df.groupby('Product Category',as_index=False,sort=True)["Sales"].count()
result

  Product Category  Sales
0             Elec      2
1            Furni      2

In [47]:
df = pd.DataFrame({
    "region": ["East","East","West","West","East","West"],
    "Sales": [200,150,300,100,250,350],
    "Manager":["A","B","C","D","E","F"]
})
df

  region  Sales Manager
0   East    200       A
1   East    150       B
2   West    300       C
3   West    100       D
4   East    250       E
5   West    350       F

In [51]:
def sales_range(x):
    return x['Sales'].max()-x['Sales'].min()

sales_data = df.groupby("region").apply(sales_range)
sales_data

region
East    100
West    250
dtype: int64

In [57]:
from numpy import median


df = pd.DataFrame({
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Salary': [50000,60000,40000,45000,70000,750000],
    'Bonus': [5000,600,2000,2500,8000,85000]
})

result = df.groupby('Department').agg(['mean',"min","max"])
result

              Salary                   Bonus
                mean    min     max     mean   min    max
Department
HR           42500.0  40000   45000   2250.0  2000   2500
IT          410000.0  70000  750000  46500.0  8000  85000
Sales        55000.0  50000   60000   2800.0   600   5000

In [58]:
result = df.groupby('Department').agg({"Salary":["min","max"],
                                       "Bonus":'sum'})
result

           Salary          Bonus
              min     max    sum
Department
HR          40000   45000   4500
IT          70000  750000  93000
Sales       50000   60000   5600

In [65]:
result = df.groupby('Department').agg(Mean_Sal=("Salary","mean"),
                                      Min_Sal=("Salary","min"),
                                      Max_Sal=("Salary","max"))
result

            Mean_Sal  Min_Sal  Max_Sal
Department
HR           42500.0    40000    45000
IT          410000.0    70000   750000
Sales        55000.0    50000    60000