In [1]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split

# Machine Learning

supervised learning, unsupervised learning, reinforcement learning, semi-supervised learning

### Supervised learning

1. Classification
2. Regression

np.map()

getdummy()

In [10]:
# Min-Max Scaling
X = np.array([1,2,3,4,5,6,7,8])
min = 0
max = 1

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min
print(X_scaled)
print(X_std)
print(X.min(axis=0))
X.max(axis=0)
print(X)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
1
[1 2 3 4 5 6 7 8]

In [16]:
data = pd.DataFrame({
    "Original ":[1,2,3,4,5,6,7,8],
    "category":["A","B","A","B","A","A","B","A"],
})
data

   Original  category
0          1        A
1          2        B
2          3        A
3          4        B
4          5        A
5          6        A
6          7        B
7          8        A

In [17]:
df = pd.get_dummies(data, columns=["category"])
df

   Original   category_A  category_B
0          1        True       False
1          2       False        True
2          3        True       False
3          4       False        True
4          5        True       False
5          6        True       False
6          7       False        True
7          8        True       False

In [27]:
df = pd.read_csv("../../../Ch1/datasets/car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [28]:
df["Car_Name"].value_counts()

Car_Name
city                   26
corolla altis          16
verna                  14
fortuner               11
brio                   10
                       ..
Hero Super Splendor     1
Hero Hunk               1
Hero  Ignitor Disc      1
Hero  CBZ Xtreme        1
Bajaj  ct 100           1
Name: count, Length: 98, dtype: int64

In [43]:
df1 = pd.get_dummies(df, columns=["Seller_Type","Transmission","Fuel_Type"], dtype=int)
df1

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol
0,ritz,2014,3.35,5.59,27000,0,1,0,0,1,0,0,1
1,sx4,2013,4.75,9.54,43000,0,1,0,0,1,0,1,0
2,ciaz,2017,7.25,9.85,6900,0,1,0,0,1,0,0,1
3,wagon r,2011,2.85,4.15,5200,0,1,0,0,1,0,0,1
4,swift,2014,4.60,6.87,42450,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,0,1,0,0,1,0,1,0
297,brio,2015,4.00,5.90,60000,0,1,0,0,1,0,0,1
298,city,2009,3.35,11.00,87934,0,1,0,0,1,0,0,1
299,city,2017,11.50,12.50,9000,0,1,0,0,1,0,1,0
300,brio,2016,5.30,5.90,5464,0,1,0,0,1,0,0,1

In [44]:
# add a new features
room_l =[18,20,10,12,18,11]
room_b = [20,20,10,11,19,10]

df = pd.DataFrame({"Length": room_l, "Breath": room_b})
df

   Length  Breath
0      18      20
1      20      20
2      10      10
3      12      11
4      18      19
5      11      10

In [46]:
df["Area"]= df["Length"]*df["Breath"]
df

   Length  Breath  Area
0      18      20   360
1      20      20   400
2      10      10   100
3      12      11   132
4      18      19   342
5      11      10   110

In [50]:
df["Type"] = np.where(df["Area"]>300, "Large", "Small")
df

   Length  Breath  Area   Type
0      18      20   360  Large
1      20      20   400  Large
2      10      10   100  Small
3      12      11   132  Small
4      18      19   342  Large
5      11      10   110  Small

In [68]:
a_area = [4720,2340,4368,3969,6142,7912]
a_price =[236000,1215000,2184000,1984500,3071000,3956000]

df= pd.DataFrame({"area": a_area, "Price": a_price})
df

   area    Price
0  4720   236000
1  2340  1215000
2  4368  2184000
3  3969  1984500
4  6142  3071000
5  7912  3956000

In [69]:
df["Price"] = np.where(df["Price"]>300000, "High",np.where(df["Price"]<200000, "Low", "Medium"))
df

   area   Price
0  4720  Medium
1  2340    High
2  4368    High
3  3969    High
4  6142    High
5  7912    High

In [7]:
# Validation Split
import pandas as pd
import numpy as np

df=pd.DataFrame({"a":[1,2,np.nan,3,4], "b":[1,5,np.nan,np.nan, 1]})

df=df.drop_duplicates(subset="b")

df.dropna()

df.fillna(20, inplace=True)
df
# print(df.shape[0])

      a     b
0   1.0   1.0
1   2.0   5.0
2  20.0  20.0

In [6]:
import pandas as pd

data = {"A": ["A1", "B2", "B2", "C3", "A1"],
        "B": [50, 40, 40, 30, 50],
        "C": [True, False, False, False, True]}

df = pd.DataFrame(data)
df = df.drop_duplicates()
# print(df.shape)
df

    A   B      C
0  A1  50   True
1  B2  40  False
3  C3  30  False