In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import plotly.express as px
import plotly.io as pio

In [3]:
# 190

data = {
    'area': [800, 1200, 1500, 2000, 2500, 3000, 3500],
    'price': [1500000, 2200000, 2800000, 3200000, 1800000, 2600000, 4000000]
}

df = pd.DataFrame(data)
df

   area    price
0   800  1500000
1  1200  2200000
2  1500  2800000
3  2000  3200000
4  2500  1800000
5  3000  2600000
6  3500  4000000

In [9]:
df["Category"] = np.where(df["price"]>3000000,"high",np.where((df["price"]<3000000)&((df["price"]>2000000)),"Medium","Low" ))
df

   area    price Category
0   800  1500000      Low
1  1200  2200000   Medium
2  1500  2800000   Medium
3  2000  3200000     high
4  2500  1800000      Low
5  3000  2600000   Medium
6  3500  4000000     high

In [10]:
# 191

data = {
    'age': [18, 25, 30, 35, 45, 60, 65, 75]
}
df = pd.DataFrame(data)
df

   age
0   18
1   25
2   30
3   35
4   45
5   60
6   65
7   75

In [12]:
df["Group"]=np.where(df["age"]<30,"Young",np.where(df["age"]>60,"Lakdi lae ne chalo","SIP na loss kario"))
df

   age               Group
0   18               Young
1   25               Young
2   30   SIP na loss kario
3   35   SIP na loss kario
4   45   SIP na loss kario
5   60   SIP na loss kario
6   65  Lakdi lae ne chalo
7   75  Lakdi lae ne chalo

In [14]:
# 192

data = {
    'income': [15000, 28000, 32000, 45000, 60000, 72000, 85000]
}
df = pd.DataFrame(data)
df

   income
0   15000
1   28000
2   32000
3   45000
4   60000
5   72000
6   85000

In [16]:
df["Category"] = np.where(
    df["income"] < 30000,
    "Low",
    np.where(
        (df["income"] >= 30000) & (df["income"] <= 70000),
        "Medium",
        "High"
    )
)
df

   income Category
0   15000      Low
1   28000      Low
2   32000   Medium
3   45000   Medium
4   60000   Medium
5   72000     High
6   85000     High