## Machine Learning

### SuperVised Learning
1. Regression
2. Classified

####  Data Cleaning

* imp: Data Transformation
* Feature Selection

#### Feature Engg

1. Feature Creation -> creating a column using existing feature 
2. Feature Transformation -> modify a column into a better one 
3. Feature Encoding -> check ts
4. Feature Selection -> remove irrelevant Feature

### one hot encoding

In [1]:
import pandas as pd 
import numpy as np 

data  = pd.DataFrame({
    'OriginalFeature': [1,2,3,4,5,6,7],
    'CategoricalFeature': ['A','B','A','B','A','B','A']
})

data

   OriginalFeature CategoricalFeature
0                1                  A
1                2                  B
2                3                  A
3                4                  B
4                5                  A
5                6                  B
6                7                  A

In [3]:
data1 = pd.get_dummies(data, columns=['CategoricalFeature'])
data1

   OriginalFeature  CategoricalFeature_A  CategoricalFeature_B
0                1                  True                 False
1                2                 False                  True
2                3                  True                 False
3                4                 False                  True
4                5                  True                 False
5                6                 False                  True
6                7                  True                 False

In [4]:
data1 = pd.get_dummies(data, columns=['CategoricalFeature'], drop_first=True)
data1

   OriginalFeature  CategoricalFeature_B
0                1                 False
1                2                  True
2                3                 False
3                4                  True
4                5                 False
5                6                  True
6                7                 False

In [6]:
carData = pd.read_csv("../../dataSets/car data.csv")
carData

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [8]:
carData['Car_Name'].value_counts()

Car_Name
city                  26
corolla altis         16
verna                 14
fortuner              11
brio                  10
                      ..
Honda Activa 125       1
Hero Hunk              1
Hero  Ignitor Disc     1
Hero  CBZ Xtreme       1
Bajaj  ct 100          1
Name: count, Length: 98, dtype: int64

In [10]:
carData.nunique()

Car_Name          98
Year              16
Selling_Price    156
Present_Price    147
Kms_Driven       206
Fuel_Type          3
Seller_Type        2
Transmission       2
Owner              3
dtype: int64

In [12]:
pd.get_dummies(carData, columns=['Fuel_Type'])

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Transmission,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol
0,ritz,2014,3.35,5.59,27000,Dealer,Manual,0,False,False,True
1,sx4,2013,4.75,9.54,43000,Dealer,Manual,0,False,True,False
2,ciaz,2017,7.25,9.85,6900,Dealer,Manual,0,False,False,True
3,wagon r,2011,2.85,4.15,5200,Dealer,Manual,0,False,False,True
4,swift,2014,4.60,6.87,42450,Dealer,Manual,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Dealer,Manual,0,False,True,False
297,brio,2015,4.00,5.90,60000,Dealer,Manual,0,False,False,True
298,city,2009,3.35,11.00,87934,Dealer,Manual,0,False,False,True
299,city,2017,11.50,12.50,9000,Dealer,Manual,0,False,True,False
300,brio,2016,5.30,5.90,5464,Dealer,Manual,0,False,False,True

In [14]:
pd.get_dummies(carData, columns=['Fuel_Type'], drop_first=True, dtype=int)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Transmission,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol
0,ritz,2014,3.35,5.59,27000,Dealer,Manual,0,0,1
1,sx4,2013,4.75,9.54,43000,Dealer,Manual,0,1,0
2,ciaz,2017,7.25,9.85,6900,Dealer,Manual,0,0,1
3,wagon r,2011,2.85,4.15,5200,Dealer,Manual,0,0,1
4,swift,2014,4.60,6.87,42450,Dealer,Manual,0,1,0
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Dealer,Manual,0,1,0
297,brio,2015,4.00,5.90,60000,Dealer,Manual,0,0,1
298,city,2009,3.35,11.00,87934,Dealer,Manual,0,0,1
299,city,2017,11.50,12.50,9000,Dealer,Manual,0,1,0
300,brio,2016,5.30,5.90,5464,Dealer,Manual,0,0,1

### Add a new Feature

In [15]:
room_len = [18,30,20,45,50]
room_b = [10,50,20,50,30]
data = pd.DataFrame({'Length':room_len, 'Breadth': room_b})
data

   Length  Breadth
0      18       10
1      30       50
2      20       20
3      45       50
4      50       30

In [16]:
data['Area'] = data['Length'] * data['Breadth']
data

   Length  Breadth  Area
0      18       10   180
1      30       50  1500
2      20       20   400
3      45       50  2250
4      50       30  1500

In [17]:
'Ture' if 1 else 0

'Ture'

In [19]:
arr = np.array([0,1,2,3,4,5,6] )
data = np.where(arr%2==1, 'Odd', np.where(arr==0, 'Medium', 'Even')) # Works as if else
data

array(['Medium', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even'], dtype='<U6')

In [25]:
ap_ar = [4720,2430,4386,3969,7912,345923]
ap_price = [2360000,1215000,2184000,19845000,3071000,2956000]

data4 = pd.DataFrame({
    'Area': ap_ar,
    'Price': ap_price
})
data4

     Area     Price
0    4720   2360000
1    2430   1215000
2    4386   2184000
3    3969  19845000
4    7912   3071000
5  345923   2956000

In [26]:
data4['Price'] = np.where(data4['Price'] > 3000000, 'High', 
                    np.where(data4['Price'] < 200000, 'Low', 'Medium'))
data4

     Area   Price
0    4720  Medium
1    2430  Medium
2    4386  Medium
3    3969    High
4    7912    High
5  345923  Medium

### Train/Test Split
1. Small DataSet: 70 train, 30 test
2. Medium DataSet: 80 - 20
3. Large Dataset 90/95 - 10/5

In [27]:
from sklearn.model_selection import train_test_split

# x = features , y = labels [ x will always be DataFrame and y will be the series]
# test_size = fraction of data
# random_state = for reproducibility 

# formula
# X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=42)




data = pd.read_csv("../../dataSets/auto-mpg.csv")
data

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [32]:
x = data[['horsepower', 'acceleration', 'mpg']]
y= data['cylinders']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1)
print(x_test.shape)

(120, 3)

In [35]:
x_train

    horsepower  acceleration   mpg
350         63          14.9  34.7
59          54          23.5  23.0
120        112          15.5  19.0
12         150           9.5  15.0
349         68          16.0  34.1
..         ...           ...   ...
393         86          15.6  27.0
255         88          15.4  25.1
72         150          12.5  15.0
235         75          18.2  26.0
37         100          15.5  18.0

[278 rows x 3 columns]

In [36]:
y_train

350    4
59     4
120    4
12     8
349    4
      ..
393    4
255    4
72     8
235    4
37     6
Name: cylinders, Length: 278, dtype: int64

In [37]:
x_test

    horsepower  acceleration   mpg
174         97          14.5  18.0
359         80          20.4  28.1
250        140          13.2  19.4
274        103          15.9  20.3
283         90          18.2  20.2
..         ...           ...   ...
382         70          16.9  34.0
39         175          11.5  14.0
171         96          13.5  24.0
271        105          16.7  23.2
247         70          18.6  39.4

[120 rows x 3 columns]

In [38]:
y_test

174    6
359    4
250    8
274    5
283    6
      ..
382    4
39     8
171    4
271    4
247    4
Name: cylinders, Length: 120, dtype: int64

#### When performing binary opreation
1. Arithmetic -> 1 + Nan = Nan
2. Logical migth return false or true depends

In [40]:
df1 = pd.DataFrame({'A': [1,2,None], 'B': [4,None,6]})
df2 = pd.DataFrame( {'A': [1,None,3], 'B': [None,5,6]} )

In [41]:
result = df1+df2
result

     A     B
0  2.0   NaN
1  NaN   NaN
2  NaN  12.0

## Cross Validation

- To evalute model's Performance by using multiple train-test splits

 it splits the data into equal parts and take one of them each time as test and other as train till all splits are covered

In [45]:
df = pd.read_csv("../../dataSets/ipl-matches.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB